apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: mongodb
        image: gcr.io/k8s-minikube/kicbase:v0.0.28
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
        valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: mongo-user
      - name: USER_PWD
       valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: mongo-user
      - name: DB_URL
       valueFrom:
        configMapKeyRef:
          name: mongo-config
          key: mongo-service
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
